import AppWalletProvider from "./components/AppWalletProvider"
import { NavBar } from "./components/NavBar"
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="crypto-bg">
        <AppWalletProvider>
          <NavBar />
          {children}
        </AppWalletProvider>
        </body>
    </html>
  )
}
